title: Tamara Köhler - PhD Researcher - EUI
description: Tamara Köhler is a PhD Researcher in Political Science at the European University Institute (EUI), studying national identity and political behavior among immigrants.
theme: jekyll-theme-minimal
